server:
   port: 8090
   
# Enabling H2 Console
spring:
   h2:
      console:
         enabled: true
         path: /h2

# Datasource
   datasource:
      url: jdbc:h2:mem:short-url
      username: sa
      password:
      driver-class-name: org.h2.Driver
